; NSIS owns installer localization independently of the Electron application locale.
LangString INSTALLER_SHORTCUTS_HEADER ${LANG_ENGLISH} "Shortcuts"
LangString INSTALLER_SHORTCUTS_HEADER ${LANG_SIMPCHINESE} "快捷方式"
LangString INSTALLER_SHORTCUTS_SUBTEXT ${LANG_ENGLISH} "Choose the shortcuts this computer gets."
LangString INSTALLER_SHORTCUTS_SUBTEXT ${LANG_SIMPCHINESE} "选择要为本机创建的快捷方式。"
LangString INSTALLER_DESKTOP_SHORTCUT ${LANG_ENGLISH} "Create a desktop shortcut"
LangString INSTALLER_DESKTOP_SHORTCUT ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString INSTALLER_START_MENU_SHORTCUT ${LANG_ENGLISH} "Add to Start menu"
LangString INSTALLER_START_MENU_SHORTCUT ${LANG_SIMPCHINESE} "添加到开始菜单"
LangString INSTALLER_RUNNING ${LANG_ENGLISH} "DeepSeek Harness is running. Close the application, then run this installer again."
LangString INSTALLER_RUNNING ${LANG_SIMPCHINESE} "DeepSeek Harness 正在运行。请先关闭应用，再重新运行安装程序。"
LangString INSTALLER_PATH_INVALID ${LANG_ENGLISH} "Choose a full local folder path. Drive roots, system folders, links and special characters are not supported."
LangString INSTALLER_PATH_INVALID ${LANG_SIMPCHINESE} "请选择本地磁盘上的完整文件夹路径，不能使用磁盘根目录、系统目录、链接目录或包含特殊字符的路径。"
LangString INSTALLER_PATH_OWNERSHIP ${LANG_ENGLISH} "Choose an empty folder or the registered DeepSeek Harness installation folder."
LangString INSTALLER_PATH_OWNERSHIP ${LANG_SIMPCHINESE} "请选择空文件夹，或 DeepSeek Harness 原来的安装目录。"
LangString INSTALLER_PATH_WRITABLE ${LANG_ENGLISH} "This location is not writable. Choose another folder."
LangString INSTALLER_PATH_WRITABLE ${LANG_SIMPCHINESE} "此位置不可写，请选择其他文件夹。"
LangString INSTALLER_DISK_SPACE ${LANG_ENGLISH} "There is not enough free disk space. Choose another location."
LangString INSTALLER_DISK_SPACE ${LANG_SIMPCHINESE} "此磁盘的可用空间不足，请选择其他位置。"